### ISSUE TITLE
Installation/Build instrctions

### ISSUE THREAD

**Issue by HexRoman** [fail0verflow/rl78-ida-proc#1]
Is there anywhere installation or building instructions? Including dependencies/environment configurations?  Or pre-compiled files to add to IDA as is?

**Comment by shuffle2** [comment]
It should compile on any platform with an appropriate makefile or whatever. The repo includes visual studio project. you can tweak the referenced ida sdk includes/libs here: https://github.com/fail0verflow/rl78-ida-proc/blob/master/vs/ida.props

dependency is ida sdk
